[book] fix the cycle fallback section to match current code
salsa-rs/salsa pull request #528
Opened 2024-07-25 03:34 UTC by carljm

Update the book section on cycle fallbacks to match what actually worked for me with the current Salsa code in main branch.

2024-07-28 09:59 UTC, nikomatsakis requested changes
Looks great, left a few nits. Is there a test case or example we can point people at?

2024-07-28 09:59 UTC, nikomatsakis commented on book/src/cycles/fallback.md
> +The recovery function has a similar signature to a query function. It is given a reference to your database along with a `salsa::Cycle` describing the cycle that occurred and the input ingredient to
```suggestion
The recovery function has a similar signature to a query function. It is given a reference to your database along with a `salsa::Cycle` describing the cycle that occurred and the arguments to the tracked function that caused the cycle; it returns the result of the query. Example:
```

2024-07-28 09:59 UTC, nikomatsakis commented on book/src/cycles/fallback.md
> +    input: MyIngredient,
```suggestion
    arg1: T1,
    ...
    argN: TN,
```

2024-07-29 16:25 UTC, carljm commented
> Is there a test case or example we can point people at?

Good call, I'll add a link to https://github.com/salsa-rs/salsa/blob/cd339fc1c9a6ea0ffb1d09bd3bffb5633f776ef3/tests/cycles.rs#L132-L141

2024-08-07 06:06 UTC, nikomatsakis approved these changes

2024-08-07 06:06 UTC, merged