Fix bug with Handle::get_mut not allowing non-mutable access to the database
salsa-rs/salsa pull request #548
Opened 2024-08-02 00:04 UTC by obsgolem

Resolves https://github.com/salsa-rs/salsa/issues/546

2024-08-02 07:29 UTC, MichaReiser commented on src/handle.rs
> +        db.runtime_mut().new_revision();
I would prefer adding a `reset_cancellation_flag()` method to `db`. Creating a new revision comes at the cost that all queries need to be verified and avoiding the `get_mut` call in user-code when there are no "write" changes might not always be possible (or complicates the code a lot)

2024-08-05 16:31 UTC, nikomatsakis requested changes
Hmm, this is probably still relevant-- can you rebase this atop master? The handle code has gone away but you should see equivalent code in storage.rs

Also, can you add a test?

Thanks! 💜

2024-08-06 09:58 UTC, MichaReiser commented
I merged in the latest changes. We only need to add some tests

2024-08-06 11:02 UTC, MichaReiser commented
I don't think this PR is still needed now that `Handle` has been removed because the only call-site of `cancel_others` is inside `zalza_mut` which always bumps the revision. 

https://github.com/salsa-rs/salsa/blob/5d3b75631bcf07e0ca62d433c53a22d6f5414c06/src/storage.rs#L99-L108

2024-08-06 16:35 UTC, nikomatsakis commented
Ah, ok, I'll close it. It may be relevant if we add some way to explicitly cancel things. Thanks @obsgolem !

2024-08-06 16:35 UTC, closed without merging