feature: Add support for dumping database contents
salsa-rs/salsa pull request #640
Opened 2024-12-29 18:43 UTC by davidbarsky

As discussed in [this HackMD](https://hackmd.io/3Mpv0fa7Rm6cn9-EH5ejkw), we want to dump the contents of a Salsa database in order to debug what rust-analyzer and Salsa are doing. The original Salsa had a [`DebugQueryTable`](https://github.com/rust-lang/rust-analyzer/blob/fa4a40bbe867ed54f5a7c905b591fd7d60ba35eb/crates/ra-salsa/src/debug.rs#L9-L29) that we'd use [like this](https://github.com/rust-lang/rust-analyzer/blob/0a706f7d2ac093985eae317781200689cfd48b78/crates/rust-analyzer/src/cli/analysis_stats.rs#L274-L286):

```rust
let mut total_file_size = Bytes::default();
for e in ide_db::base_db::ParseQuery.in_db(db).entries::<Vec<_>>() {
    total_file_size += syntax_len(db.parse(e.key).syntax_node())
}

let mut total_macro_file_size = Bytes::default();
for e in hir::db::ParseMacroExpansionQuery.in_db(db).entries::<Vec<_>>() {
    let val = db.parse_macro_expansion(e.key).value.0;
    total_macro_file_size += syntax_len(val.syntax_node())
}
eprintln!("source files: {total_file_size}, macro files: {total_macro_file_size}");
```

(`ParseQuery` and `ParseMacroExpansionQuery` [were generated](https://github.com/rust-lang/rust-analyzer/blob/59bc7b49d0ad319de8c477c63da552cbc8a05e4c/crates/ra-salsa/ra-salsa-macros/src/query_group.rs#L43-L44) from [`SourceDatabase::parse`](https://github.com/rust-lang/rust-analyzer/blob/59bc7b49d0ad319de8c477c63da552cbc8a05e4c/crates/base-db/src/lib.rs#L69C8-L69C13) and [`ExpandDatabase::parse_macro_expansion`](https://github.com/rust-lang/rust-analyzer/blob/59bc7b49d0ad319de8c477c63da552cbc8a05e4c/crates/hir-expand/src/db.rs#L69-L73), respectively.)

This PR takes a slightly different approach: instead of generating a `Query` struct corresponding to a tracked function or Salsa struct, this PR simply exposes the underlying pages on `salsa::Storage` via the `debug_input_entries`, `debug_input_entries`, and `debug_interned_entries` methods. This results in the following API:

```
let _ = InternedStruct::new(&db, "Hello, world!".to_string());

// test interned structs
let interned = db
    .storage()
    .debug_interned_entries::<InternedStruct>()
    .collect::<Vec<_>>();
```

2025-01-27 21:12 UTC, nikomatsakis requested changes
This PR seems fine. I left some nits. I'm of mixed minds about exposing the fields directly. Also, returning a `&(A, B, C)` means that the data *must* store tuples directly, which perhaps we might want to change at some point.

I am thinking about returning a `(&A, &B, &C)` tuple... we'd have to do a bit more work to do that, but it would be very flexible if we wanted to refactor away from storing a tuple.

2025-01-27 21:12 UTC, nikomatsakis commented on src/storage.rs
> +        let zalza = self.zalsa_impl();
```suggestion
        let zalsa = self.zalsa_impl();
```

2025-01-27 21:12 UTC, nikomatsakis commented on src/storage.rs
> +        zalza
```suggestion
        zalsa
```

2025-01-27 21:12 UTC, nikomatsakis commented on src/tracked_struct.rs
> +    pub fields: C::Fields<'static>,
Why is this public? That sounds a bit worrisome.

2025-01-27 21:12 UTC, nikomatsakis commented on src/interned.rs
> +    pub data: C::Data<'static>,
it feels like this should be renamed to `fields` for consistency; maybe `C::Fields`, even

2025-01-29 15:46 UTC, davidbarsky commented
> This PR seems fine. I left some nits. I'm of mixed minds about exposing the fields directly. Also, returning a `&(A, B, C)` means that the data _must_ store tuples directly, which perhaps we might want to change at some point.

I'm also of mixed minds of exposing fields directly; it doesn't feel _great_.

> I am thinking about returning a `(&A, &B, &C)` tuple... we'd have to do a bit more work to do that, but it would be very flexible if we wanted to refactor away from storing a tuple.

I like the `(&A, &B, &C)` idea. I initially wrote a longer response proposing that we'd use a dedicated/standalone struct for this, but I realized that it's effectively a named variant of `(&A, &B, &C)` and raises questions about how and when said struct would be generated.

Anyways, for immediate next steps, I'll extend this to the outputs of tracked functions and fix some of nits. Longer term, I'm unsure if I'd like to revisit this before a 1.0 (moving to the `(&A, &B, &C)` approach) or feature-flagging this functionality behind an unstable feature flag. To expand on the former, I haven't looked into what work the `(&A, &B, &C)` approach entails, but I worry it requires writing some trait implementations for tuples of different lengths, but the flexibility to evolve is pretty darn compelling.

2025-01-30 20:44 UTC, nikomatsakis commented
@davidbarsky that sounds good to me. Maybe move it under a feature before we land?

2025-01-31 16:13 UTC, davidbarsky commented
@nikomatsakis Yeah. I'll move this to be under a Cargo feature instead of a `RUSTFLAG`, but I'll name it something like `unstable-debug` and say its exempt from semver. I also may the dumping a tracked function's outputs since I think the changes here might be sufficient for rust-analyzer's needs, but I don't know yet.

2025-01-31 17:57 UTC, nikomatsakis commented
@davidbarsky I propose you call it something like `semver-exempt-debug` and also that we rename [the `plumbing` module](https://github.com/salsa-rs/salsa/blob/master/src/lib.rs#L68) to be `semver-exempt`.

2025-01-31 17:57 UTC, nikomatsakis commented
or `semver-unstable`? idk, is there a widely used convention for this?

2025-01-31 17:58 UTC, nikomatsakis commented
in any case I'd prefer not to land this PR without the cargo feature, but we can if you like

2025-01-31 18:41 UTC, nikomatsakis commented
Agreed that renaming the plumbing module should be separate. I like the name semver-unstable.

2025-01-31 18:42 UTC, nikomatsakis commented
I'm indifferent about RUST FLAGS vs not as long as the name clearly signals the instability

2025-01-31 19:57 UTC, nikomatsakis approved these changes

2025-01-31 19:58 UTC, nikomatsakis commented on Cargo.toml
> +default = ["salsa_unstable"]
This can wait until a future PR, but I think we want to tweak the testing setup so that this feature is not included for (most) tests.

2025-01-31 19:59 UTC, merged